mode: yoro

name: coating
device: auto
construct:
  width: 224
  height: 224
  anchor:
    - [[42.48, 45.48], [46.14, 34.85]]

  deg_min: -180
  deg_max: 180
  deg_part_size: 10
  backbone:
    name: 'yoro.backbones.ResNet_FCN'
    args: {model_name: resnet18}

train_param:

  batch: 64

  max_iter: 30000
  esti_iter: 500
  bak_iter: 500

  train_units: 0
  moving_factor: 0.01
  evaluator:
    conf_threshold: 0.5
    nms_threshold: 0.6
    sim_threshold: [0.5, 0.95, 0.05]

  num_workers: 8
  pin_memory: true
  optimizer:
    name: 'torch.optim.Adam'
    args: {'lr': 0.001, 'weight_decay': 0.0005}

  anchor_thresh: 0.5
  anchor_max_count: 1

dataset:
  names_file: ~/dataset/coating/coating.names
  train_dir: ~/dataset/coating/train
  valid_dir: ~/dataset/coating/valid

transform:
  brightness: 0.3
  contrast: 0.3
  saturation: 0.3
  hue: 0.1
  degrees: 30
  translate: [0.3, 0.3]
  scale: [0.7, 1.3]
  apply_on_valid: false
