name: rotation_regressor
device: auto
construct:
  width: 224
  height: 224
  deg_min: -45
  deg_max: 45
  backbone:
    name: 'torchvision.models.resnet18'
    args: {num_classes: 1}

train_param:
  max_epoch: 1000
  esti_epoch: 100
  bak_epoch: 1000
  batch: 16
  num_workers: 8
  optimizer:
    name: Adam
    args: {}

dataset:
  names_file: ~/dataset/PlateShelf_Mark_Train/data.names
  train_dir: ~/dataset/PlateShelf_Mark_Train
  valid_dir: ~/dataset/PlateShelf_Mark_Test

transform:
  brightness: 0.3
  contrast: 0.3
  saturation: 0.3
  hue: 0.1
  translate: [0.3, 0.3]
  scale: [0.7, 1.3]
  apply_on_valid: false
