mode: rotreg

name: rotation_regressor
device: auto
construct:
  width: 224
  height: 224
  deg_min: -45
  deg_max: 45
  backbone:
    name: 'yoro.backbones.ResNet_Feature'
    args: {model_name: resnet18}

train_param:

  batch: 64

  max_iter: 100000
  esti_iter: 1000
  bak_iter: 1000

  num_workers: 8
  pin_memory: true
  optimizer:
    name: 'torch.optim.SGD'
    args: {'lr': 0.0001, 'momentum': 0.9}

dataset:
  names_file: ~/dataset/PlateShelf/data.names
  train_dir: ~/dataset/PlateShelf/train
  valid_dir: ~/dataset/PlateShelf/valid

transform:
  brightness: 0.3
  contrast: 0.3
  saturation: 0.3
  hue: 0.1
  translate: [0.3, 0.3]
  scale: [0.7, 1.3]
  apply_on_valid: false
