mode: rotanc

name: rotation_anchor
device: auto
construct:
  width: 224
  height: 224
  deg_min: -45
  deg_max: 45
  deg_part_size: 10
  backbone:
    name: 'torchvision.models.resnet18'
    args: {}

train_param:
  max_epoch: 500
  esti_epoch: 10
  bak_epoch: 100
  batch: 64
  num_workers: 8
  pin_memory: true
  optimizer:
    name: SGD
    args: {'lr': 0.0001, 'momentum': 0.9}

dataset:
  names_file: ~/dataset/PlateShelf/data.names
  train_dir: ~/dataset/PlateShelf/train
  valid_dir: ~/dataset/PlateShelf/valid

transform:
  brightness: 0.3
  contrast: 0.3
  saturation: 0.3
  hue: 0.1
  translate: [0.3, 0.3]
  scale: [0.7, 1.3]
  apply_on_valid: false
